#!/usr/bin/env node
/**
 * Writes src/generated/version.ts from the current git state.
 *
 * The app version in app.json drives the runtime version, and updates only
 * reach an installed build whose runtime version matches — so it changes only
 * when the native side does, not per release. The number that counts up on
 * every push lives here instead: the commit count, which never needs
 * maintaining. The app version is copied along so the About card cannot
 * drift away from what app.json actually says.
 *
 * Runs in CI right before `eas update`, so whatever gets bundled carries the
 * state it was built from.
 */

const { execSync } = require('child_process');
const { writeFileSync, mkdirSync } = require('fs');
const { join, dirname } = require('path');

const OUT = join(__dirname, '..', 'src', 'generated', 'version.ts');
const APP_VERSION = require(join(__dirname, '..', 'app.json')).expo.version;

function git(command, fallback) {
  try {
    return execSync(`git ${command}`, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return fallback;
  }
}

const build = parseInt(git('rev-list --count HEAD', '0'), 10) || 0;
const commit = git('rev-parse --short HEAD', 'unknown');
const builtAt = new Date().toISOString();

const contents = `// AUTO-GENERATED by scripts/generate-version.js — do not edit by hand.
// Regenerated on every publish; the checked-in values are only a fallback
// for local development.

export const APP_VERSION = '${APP_VERSION}';
export const BUILD_NUMBER = ${build};
export const COMMIT = '${commit}';
export const BUILT_AT = '${builtAt}';
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, contents);

console.log(`version.ts → ${APP_VERSION} Build ${build} (${commit})`);
